// source: protos/Authentication/page.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var protobuf_infrastructure_pb = require('../../protobuf/infrastructure_pb.js');
goog.object.extend(proto, protobuf_infrastructure_pb);
goog.exportSymbol('proto.Soit.Authentication.CreatePageRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.FindPageReply', null, global);
goog.exportSymbol('proto.Soit.Authentication.FindPageReply.Element', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdatePageRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.CreatePageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.CreatePageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.CreatePageRequest.displayName = 'proto.Soit.Authentication.CreatePageRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.FindPageReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.FindPageReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.FindPageReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.FindPageReply.displayName = 'proto.Soit.Authentication.FindPageReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.FindPageReply.Element = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.FindPageReply.Element, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.FindPageReply.Element.displayName = 'proto.Soit.Authentication.FindPageReply.Element';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdatePageRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.UpdatePageRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdatePageRequest.displayName = 'proto.Soit.Authentication.UpdatePageRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.CreatePageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.CreatePageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.CreatePageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    moduleId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    key: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    no: jspb.Message.getFieldWithDefault(msg, 4, 0),
    icon: jspb.Message.getFieldWithDefault(msg, 5, ""),
    route: jspb.Message.getFieldWithDefault(msg, 6, ""),
    showInMenu: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.CreatePageRequest}
 */
proto.Soit.Authentication.CreatePageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.CreatePageRequest;
  return proto.Soit.Authentication.CreatePageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.CreatePageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.CreatePageRequest}
 */
proto.Soit.Authentication.CreatePageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setModuleId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNo(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setIcon(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoute(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShowInMenu(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.CreatePageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.CreatePageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.CreatePageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModuleId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNo();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getIcon();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRoute();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getShowInMenu();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional int64 module_id = 1;
 * @return {number}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.getModuleId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.CreatePageRequest} returns this
 */
proto.Soit.Authentication.CreatePageRequest.prototype.setModuleId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string key = 2;
 * @return {string}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreatePageRequest} returns this
 */
proto.Soit.Authentication.CreatePageRequest.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreatePageRequest} returns this
 */
proto.Soit.Authentication.CreatePageRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 no = 4;
 * @return {number}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.getNo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.CreatePageRequest} returns this
 */
proto.Soit.Authentication.CreatePageRequest.prototype.setNo = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string icon = 5;
 * @return {string}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.getIcon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreatePageRequest} returns this
 */
proto.Soit.Authentication.CreatePageRequest.prototype.setIcon = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string route = 6;
 * @return {string}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.getRoute = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreatePageRequest} returns this
 */
proto.Soit.Authentication.CreatePageRequest.prototype.setRoute = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bool show_in_menu = 7;
 * @return {boolean}
 */
proto.Soit.Authentication.CreatePageRequest.prototype.getShowInMenu = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Soit.Authentication.CreatePageRequest} returns this
 */
proto.Soit.Authentication.CreatePageRequest.prototype.setShowInMenu = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.FindPageReply.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.FindPageReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.FindPageReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.FindPageReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindPageReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    module: (f = msg.getModule()) && protobuf_infrastructure_pb.NamedIdentify.toObject(includeInstance, f),
    key: jspb.Message.getFieldWithDefault(msg, 3, ""),
    name: jspb.Message.getFieldWithDefault(msg, 4, ""),
    no: jspb.Message.getFieldWithDefault(msg, 5, 0),
    icon: jspb.Message.getFieldWithDefault(msg, 6, ""),
    route: jspb.Message.getFieldWithDefault(msg, 7, ""),
    showInMenu: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    elementsList: jspb.Message.toObjectList(msg.getElementsList(),
    proto.Soit.Authentication.FindPageReply.Element.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.FindPageReply}
 */
proto.Soit.Authentication.FindPageReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.FindPageReply;
  return proto.Soit.Authentication.FindPageReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.FindPageReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.FindPageReply}
 */
proto.Soit.Authentication.FindPageReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = new protobuf_infrastructure_pb.NamedIdentify;
      reader.readMessage(value,protobuf_infrastructure_pb.NamedIdentify.deserializeBinaryFromReader);
      msg.setModule(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNo(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setIcon(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoute(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShowInMenu(value);
      break;
    case 9:
      var value = new proto.Soit.Authentication.FindPageReply.Element;
      reader.readMessage(value,proto.Soit.Authentication.FindPageReply.Element.deserializeBinaryFromReader);
      msg.addElements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.FindPageReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.FindPageReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.FindPageReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindPageReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getModule();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      protobuf_infrastructure_pb.NamedIdentify.serializeBinaryToWriter
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNo();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getIcon();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRoute();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getShowInMenu();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getElementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.Soit.Authentication.FindPageReply.Element.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.FindPageReply.Element.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.FindPageReply.Element} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindPageReply.Element.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    key: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    style: jspb.Message.getFieldWithDefault(msg, 5, ""),
    icon: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.FindPageReply.Element}
 */
proto.Soit.Authentication.FindPageReply.Element.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.FindPageReply.Element;
  return proto.Soit.Authentication.FindPageReply.Element.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.FindPageReply.Element} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.FindPageReply.Element}
 */
proto.Soit.Authentication.FindPageReply.Element.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {!proto.Soit.Infrastructure.ElementTypes} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStyle(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setIcon(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.FindPageReply.Element.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.FindPageReply.Element} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindPageReply.Element.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getStyle();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIcon();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.FindPageReply.Element} returns this
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string key = 2;
 * @return {string}
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindPageReply.Element} returns this
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindPageReply.Element} returns this
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Soit.Infrastructure.ElementTypes type = 4;
 * @return {!proto.Soit.Infrastructure.ElementTypes}
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.getType = function() {
  return /** @type {!proto.Soit.Infrastructure.ElementTypes} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.ElementTypes} value
 * @return {!proto.Soit.Authentication.FindPageReply.Element} returns this
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string style = 5;
 * @return {string}
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.getStyle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindPageReply.Element} returns this
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.setStyle = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string icon = 6;
 * @return {string}
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.getIcon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindPageReply.Element} returns this
 */
proto.Soit.Authentication.FindPageReply.Element.prototype.setIcon = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.FindPageReply.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional Soit.Infrastructure.NamedIdentify module = 2;
 * @return {?proto.Soit.Infrastructure.NamedIdentify}
 */
proto.Soit.Authentication.FindPageReply.prototype.getModule = function() {
  return /** @type{?proto.Soit.Infrastructure.NamedIdentify} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.NamedIdentify, 2));
};


/**
 * @param {?proto.Soit.Infrastructure.NamedIdentify|undefined} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
*/
proto.Soit.Authentication.FindPageReply.prototype.setModule = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.clearModule = function() {
  return this.setModule(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.Authentication.FindPageReply.prototype.hasModule = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string key = 3;
 * @return {string}
 */
proto.Soit.Authentication.FindPageReply.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.Soit.Authentication.FindPageReply.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 no = 5;
 * @return {number}
 */
proto.Soit.Authentication.FindPageReply.prototype.getNo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.setNo = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string icon = 6;
 * @return {string}
 */
proto.Soit.Authentication.FindPageReply.prototype.getIcon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.setIcon = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string route = 7;
 * @return {string}
 */
proto.Soit.Authentication.FindPageReply.prototype.getRoute = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.setRoute = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bool show_in_menu = 8;
 * @return {boolean}
 */
proto.Soit.Authentication.FindPageReply.prototype.getShowInMenu = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.setShowInMenu = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * repeated Element elements = 9;
 * @return {!Array<!proto.Soit.Authentication.FindPageReply.Element>}
 */
proto.Soit.Authentication.FindPageReply.prototype.getElementsList = function() {
  return /** @type{!Array<!proto.Soit.Authentication.FindPageReply.Element>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Soit.Authentication.FindPageReply.Element, 9));
};


/**
 * @param {!Array<!proto.Soit.Authentication.FindPageReply.Element>} value
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
*/
proto.Soit.Authentication.FindPageReply.prototype.setElementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.Soit.Authentication.FindPageReply.Element=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.FindPageReply.Element}
 */
proto.Soit.Authentication.FindPageReply.prototype.addElements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.Soit.Authentication.FindPageReply.Element, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.FindPageReply} returns this
 */
proto.Soit.Authentication.FindPageReply.prototype.clearElementsList = function() {
  return this.setElementsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdatePageRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdatePageRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdatePageRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    moduleId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    key: jspb.Message.getFieldWithDefault(msg, 3, ""),
    name: jspb.Message.getFieldWithDefault(msg, 4, ""),
    no: jspb.Message.getFieldWithDefault(msg, 5, 0),
    icon: jspb.Message.getFieldWithDefault(msg, 6, ""),
    route: jspb.Message.getFieldWithDefault(msg, 7, ""),
    showInMenu: jspb.Message.getBooleanFieldWithDefault(msg, 8, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdatePageRequest}
 */
proto.Soit.Authentication.UpdatePageRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdatePageRequest;
  return proto.Soit.Authentication.UpdatePageRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdatePageRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdatePageRequest}
 */
proto.Soit.Authentication.UpdatePageRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setModuleId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNo(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setIcon(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoute(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShowInMenu(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdatePageRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdatePageRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdatePageRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getModuleId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getNo();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getIcon();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRoute();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getShowInMenu();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdatePageRequest} returns this
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 module_id = 2;
 * @return {number}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.getModuleId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdatePageRequest} returns this
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.setModuleId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string key = 3;
 * @return {string}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdatePageRequest} returns this
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdatePageRequest} returns this
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 no = 5;
 * @return {number}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.getNo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdatePageRequest} returns this
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.setNo = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string icon = 6;
 * @return {string}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.getIcon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdatePageRequest} returns this
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.setIcon = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string route = 7;
 * @return {string}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.getRoute = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdatePageRequest} returns this
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.setRoute = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bool show_in_menu = 8;
 * @return {boolean}
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.getShowInMenu = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Soit.Authentication.UpdatePageRequest} returns this
 */
proto.Soit.Authentication.UpdatePageRequest.prototype.setShowInMenu = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


goog.object.extend(exports, proto.Soit.Authentication);
