// source: protos/Authentication/role.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var protobuf_infrastructure_pb = require('../../protobuf/infrastructure_pb.js');
goog.object.extend(proto, protobuf_infrastructure_pb);
goog.exportSymbol('proto.Soit.Authentication.ComponentTreeNode', null, global);
goog.exportSymbol('proto.Soit.Authentication.ComponentTreeNode.NodeTypes', null, global);
goog.exportSymbol('proto.Soit.Authentication.CreateRoleRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.FindRoleReply', null, global);
goog.exportSymbol('proto.Soit.Authentication.FindRoleReply.User', null, global);
goog.exportSymbol('proto.Soit.Authentication.GetRoleComponentTreeReply', null, global);
goog.exportSymbol('proto.Soit.Authentication.QueryRoleReply', null, global);
goog.exportSymbol('proto.Soit.Authentication.QueryRoleRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdateRoleComponentsRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdateRoleRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdateRoleStatesRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdateRoleUsersRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.ComponentTreeNode = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.ComponentTreeNode.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.ComponentTreeNode, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.ComponentTreeNode.displayName = 'proto.Soit.Authentication.ComponentTreeNode';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.CreateRoleRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.CreateRoleRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.CreateRoleRequest.displayName = 'proto.Soit.Authentication.CreateRoleRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.FindRoleReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.FindRoleReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.FindRoleReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.FindRoleReply.displayName = 'proto.Soit.Authentication.FindRoleReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.FindRoleReply.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.FindRoleReply.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.FindRoleReply.User.displayName = 'proto.Soit.Authentication.FindRoleReply.User';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.GetRoleComponentTreeReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.GetRoleComponentTreeReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.GetRoleComponentTreeReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.GetRoleComponentTreeReply.displayName = 'proto.Soit.Authentication.GetRoleComponentTreeReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.QueryRoleReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.QueryRoleReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.QueryRoleReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.QueryRoleReply.displayName = 'proto.Soit.Authentication.QueryRoleReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.QueryRoleRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.QueryRoleRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.QueryRoleRequest.displayName = 'proto.Soit.Authentication.QueryRoleRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.UpdateRoleComponentsRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.UpdateRoleComponentsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdateRoleComponentsRequest.displayName = 'proto.Soit.Authentication.UpdateRoleComponentsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdateRoleRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.UpdateRoleRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdateRoleRequest.displayName = 'proto.Soit.Authentication.UpdateRoleRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdateRoleStatesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.UpdateRoleStatesRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.UpdateRoleStatesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdateRoleStatesRequest.displayName = 'proto.Soit.Authentication.UpdateRoleStatesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdateRoleUsersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.UpdateRoleUsersRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.UpdateRoleUsersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdateRoleUsersRequest.displayName = 'proto.Soit.Authentication.UpdateRoleUsersRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.ComponentTreeNode.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.ComponentTreeNode.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.ComponentTreeNode} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.ComponentTreeNode.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    icon: jspb.Message.getFieldWithDefault(msg, 3, ""),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    key: jspb.Message.getFieldWithDefault(msg, 5, ""),
    no: jspb.Message.getFieldWithDefault(msg, 6, 0),
    route: jspb.Message.getFieldWithDefault(msg, 7, ""),
    showInMenu: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    childrenList: jspb.Message.toObjectList(msg.getChildrenList(),
    proto.Soit.Authentication.ComponentTreeNode.toObject, includeInstance),
    enabled: jspb.Message.getBooleanFieldWithDefault(msg, 10, false),
    parentId: (f = msg.getParentId()) && google_protobuf_wrappers_pb.Int64Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.ComponentTreeNode}
 */
proto.Soit.Authentication.ComponentTreeNode.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.ComponentTreeNode;
  return proto.Soit.Authentication.ComponentTreeNode.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.ComponentTreeNode} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.ComponentTreeNode}
 */
proto.Soit.Authentication.ComponentTreeNode.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setIcon(value);
      break;
    case 4:
      var value = /** @type {!proto.Soit.Authentication.ComponentTreeNode.NodeTypes} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNo(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRoute(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShowInMenu(value);
      break;
    case 9:
      var value = new proto.Soit.Authentication.ComponentTreeNode;
      reader.readMessage(value,proto.Soit.Authentication.ComponentTreeNode.deserializeBinaryFromReader);
      msg.addChildren(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnabled(value);
      break;
    case 11:
      var value = new google_protobuf_wrappers_pb.Int64Value;
      reader.readMessage(value,google_protobuf_wrappers_pb.Int64Value.deserializeBinaryFromReader);
      msg.setParentId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.ComponentTreeNode.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.ComponentTreeNode} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.ComponentTreeNode.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIcon();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getNo();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getRoute();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getShowInMenu();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getChildrenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.Soit.Authentication.ComponentTreeNode.serializeBinaryToWriter
    );
  }
  f = message.getEnabled();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
  f = message.getParentId();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_wrappers_pb.Int64Value.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.Soit.Authentication.ComponentTreeNode.NodeTypes = {
  MODULE: 0,
  PAGE: 1,
  ELEMENT: 2
};

/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string icon = 3;
 * @return {string}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getIcon = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setIcon = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional NodeTypes type = 4;
 * @return {!proto.Soit.Authentication.ComponentTreeNode.NodeTypes}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getType = function() {
  return /** @type {!proto.Soit.Authentication.ComponentTreeNode.NodeTypes} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.Soit.Authentication.ComponentTreeNode.NodeTypes} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string key = 5;
 * @return {string}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 no = 6;
 * @return {number}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getNo = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setNo = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string route = 7;
 * @return {string}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getRoute = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setRoute = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bool show_in_menu = 8;
 * @return {boolean}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getShowInMenu = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setShowInMenu = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * repeated ComponentTreeNode children = 9;
 * @return {!Array<!proto.Soit.Authentication.ComponentTreeNode>}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getChildrenList = function() {
  return /** @type{!Array<!proto.Soit.Authentication.ComponentTreeNode>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Soit.Authentication.ComponentTreeNode, 9));
};


/**
 * @param {!Array<!proto.Soit.Authentication.ComponentTreeNode>} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
*/
proto.Soit.Authentication.ComponentTreeNode.prototype.setChildrenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.Soit.Authentication.ComponentTreeNode=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.ComponentTreeNode}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.addChildren = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.Soit.Authentication.ComponentTreeNode, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.clearChildrenList = function() {
  return this.setChildrenList([]);
};


/**
 * optional bool enabled = 10;
 * @return {boolean}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.setEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};


/**
 * optional google.protobuf.Int64Value parent_id = 11;
 * @return {?proto.google.protobuf.Int64Value}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.getParentId = function() {
  return /** @type{?proto.google.protobuf.Int64Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int64Value, 11));
};


/**
 * @param {?proto.google.protobuf.Int64Value|undefined} value
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
*/
proto.Soit.Authentication.ComponentTreeNode.prototype.setParentId = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.Authentication.ComponentTreeNode} returns this
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.clearParentId = function() {
  return this.setParentId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.Authentication.ComponentTreeNode.prototype.hasParentId = function() {
  return jspb.Message.getField(this, 11) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.CreateRoleRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.CreateRoleRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.CreateRoleRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.CreateRoleRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    state: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.CreateRoleRequest}
 */
proto.Soit.Authentication.CreateRoleRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.CreateRoleRequest;
  return proto.Soit.Authentication.CreateRoleRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.CreateRoleRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.CreateRoleRequest}
 */
proto.Soit.Authentication.CreateRoleRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {!proto.Soit.Infrastructure.EntityStates} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.CreateRoleRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.CreateRoleRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.CreateRoleRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.CreateRoleRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Soit.Authentication.CreateRoleRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateRoleRequest} returns this
 */
proto.Soit.Authentication.CreateRoleRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.Soit.Authentication.CreateRoleRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateRoleRequest} returns this
 */
proto.Soit.Authentication.CreateRoleRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Soit.Infrastructure.EntityStates state = 3;
 * @return {!proto.Soit.Infrastructure.EntityStates}
 */
proto.Soit.Authentication.CreateRoleRequest.prototype.getState = function() {
  return /** @type {!proto.Soit.Infrastructure.EntityStates} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.EntityStates} value
 * @return {!proto.Soit.Authentication.CreateRoleRequest} returns this
 */
proto.Soit.Authentication.CreateRoleRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.FindRoleReply.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.FindRoleReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.FindRoleReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.FindRoleReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindRoleReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    state: jspb.Message.getFieldWithDefault(msg, 4, 0),
    usersList: jspb.Message.toObjectList(msg.getUsersList(),
    proto.Soit.Authentication.FindRoleReply.User.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.FindRoleReply}
 */
proto.Soit.Authentication.FindRoleReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.FindRoleReply;
  return proto.Soit.Authentication.FindRoleReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.FindRoleReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.FindRoleReply}
 */
proto.Soit.Authentication.FindRoleReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {!proto.Soit.Infrastructure.EntityStates} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 5:
      var value = new proto.Soit.Authentication.FindRoleReply.User;
      reader.readMessage(value,proto.Soit.Authentication.FindRoleReply.User.deserializeBinaryFromReader);
      msg.addUsers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.FindRoleReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.FindRoleReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.FindRoleReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindRoleReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getUsersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.Soit.Authentication.FindRoleReply.User.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.FindRoleReply.User.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.FindRoleReply.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.FindRoleReply.User} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindRoleReply.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    legalName: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.FindRoleReply.User}
 */
proto.Soit.Authentication.FindRoleReply.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.FindRoleReply.User;
  return proto.Soit.Authentication.FindRoleReply.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.FindRoleReply.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.FindRoleReply.User}
 */
proto.Soit.Authentication.FindRoleReply.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLegalName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.FindRoleReply.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.FindRoleReply.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.FindRoleReply.User} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindRoleReply.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLegalName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.FindRoleReply.User.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.FindRoleReply.User} returns this
 */
proto.Soit.Authentication.FindRoleReply.User.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Soit.Authentication.FindRoleReply.User.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindRoleReply.User} returns this
 */
proto.Soit.Authentication.FindRoleReply.User.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string legal_name = 3;
 * @return {string}
 */
proto.Soit.Authentication.FindRoleReply.User.prototype.getLegalName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindRoleReply.User} returns this
 */
proto.Soit.Authentication.FindRoleReply.User.prototype.setLegalName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.FindRoleReply.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.FindRoleReply} returns this
 */
proto.Soit.Authentication.FindRoleReply.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Soit.Authentication.FindRoleReply.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindRoleReply} returns this
 */
proto.Soit.Authentication.FindRoleReply.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.Soit.Authentication.FindRoleReply.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindRoleReply} returns this
 */
proto.Soit.Authentication.FindRoleReply.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Soit.Infrastructure.EntityStates state = 4;
 * @return {!proto.Soit.Infrastructure.EntityStates}
 */
proto.Soit.Authentication.FindRoleReply.prototype.getState = function() {
  return /** @type {!proto.Soit.Infrastructure.EntityStates} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.EntityStates} value
 * @return {!proto.Soit.Authentication.FindRoleReply} returns this
 */
proto.Soit.Authentication.FindRoleReply.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * repeated User users = 5;
 * @return {!Array<!proto.Soit.Authentication.FindRoleReply.User>}
 */
proto.Soit.Authentication.FindRoleReply.prototype.getUsersList = function() {
  return /** @type{!Array<!proto.Soit.Authentication.FindRoleReply.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Soit.Authentication.FindRoleReply.User, 5));
};


/**
 * @param {!Array<!proto.Soit.Authentication.FindRoleReply.User>} value
 * @return {!proto.Soit.Authentication.FindRoleReply} returns this
*/
proto.Soit.Authentication.FindRoleReply.prototype.setUsersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.Soit.Authentication.FindRoleReply.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.FindRoleReply.User}
 */
proto.Soit.Authentication.FindRoleReply.prototype.addUsers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.Soit.Authentication.FindRoleReply.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.FindRoleReply} returns this
 */
proto.Soit.Authentication.FindRoleReply.prototype.clearUsersList = function() {
  return this.setUsersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.GetRoleComponentTreeReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.GetRoleComponentTreeReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    nodesList: jspb.Message.toObjectList(msg.getNodesList(),
    proto.Soit.Authentication.ComponentTreeNode.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.GetRoleComponentTreeReply}
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.GetRoleComponentTreeReply;
  return proto.Soit.Authentication.GetRoleComponentTreeReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.GetRoleComponentTreeReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.GetRoleComponentTreeReply}
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Soit.Authentication.ComponentTreeNode;
      reader.readMessage(value,proto.Soit.Authentication.ComponentTreeNode.deserializeBinaryFromReader);
      msg.addNodes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.GetRoleComponentTreeReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.GetRoleComponentTreeReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNodesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.Soit.Authentication.ComponentTreeNode.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ComponentTreeNode nodes = 1;
 * @return {!Array<!proto.Soit.Authentication.ComponentTreeNode>}
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.prototype.getNodesList = function() {
  return /** @type{!Array<!proto.Soit.Authentication.ComponentTreeNode>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Soit.Authentication.ComponentTreeNode, 1));
};


/**
 * @param {!Array<!proto.Soit.Authentication.ComponentTreeNode>} value
 * @return {!proto.Soit.Authentication.GetRoleComponentTreeReply} returns this
*/
proto.Soit.Authentication.GetRoleComponentTreeReply.prototype.setNodesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Soit.Authentication.ComponentTreeNode=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.ComponentTreeNode}
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.prototype.addNodes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Soit.Authentication.ComponentTreeNode, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.GetRoleComponentTreeReply} returns this
 */
proto.Soit.Authentication.GetRoleComponentTreeReply.prototype.clearNodesList = function() {
  return this.setNodesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.QueryRoleReply.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.QueryRoleReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.QueryRoleReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.QueryRoleReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.QueryRoleReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageResult: (f = msg.getPageResult()) && protobuf_infrastructure_pb.PageResult.toObject(includeInstance, f),
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.Soit.Authentication.FindRoleReply.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.QueryRoleReply}
 */
proto.Soit.Authentication.QueryRoleReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.QueryRoleReply;
  return proto.Soit.Authentication.QueryRoleReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.QueryRoleReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.QueryRoleReply}
 */
proto.Soit.Authentication.QueryRoleReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protobuf_infrastructure_pb.PageResult;
      reader.readMessage(value,protobuf_infrastructure_pb.PageResult.deserializeBinaryFromReader);
      msg.setPageResult(value);
      break;
    case 2:
      var value = new proto.Soit.Authentication.FindRoleReply;
      reader.readMessage(value,proto.Soit.Authentication.FindRoleReply.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.QueryRoleReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.QueryRoleReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.QueryRoleReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.QueryRoleReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageResult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protobuf_infrastructure_pb.PageResult.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Soit.Authentication.FindRoleReply.serializeBinaryToWriter
    );
  }
};


/**
 * optional Soit.Infrastructure.PageResult page_result = 1;
 * @return {?proto.Soit.Infrastructure.PageResult}
 */
proto.Soit.Authentication.QueryRoleReply.prototype.getPageResult = function() {
  return /** @type{?proto.Soit.Infrastructure.PageResult} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.PageResult, 1));
};


/**
 * @param {?proto.Soit.Infrastructure.PageResult|undefined} value
 * @return {!proto.Soit.Authentication.QueryRoleReply} returns this
*/
proto.Soit.Authentication.QueryRoleReply.prototype.setPageResult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.Authentication.QueryRoleReply} returns this
 */
proto.Soit.Authentication.QueryRoleReply.prototype.clearPageResult = function() {
  return this.setPageResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.Authentication.QueryRoleReply.prototype.hasPageResult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated FindRoleReply items = 2;
 * @return {!Array<!proto.Soit.Authentication.FindRoleReply>}
 */
proto.Soit.Authentication.QueryRoleReply.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.Soit.Authentication.FindRoleReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Soit.Authentication.FindRoleReply, 2));
};


/**
 * @param {!Array<!proto.Soit.Authentication.FindRoleReply>} value
 * @return {!proto.Soit.Authentication.QueryRoleReply} returns this
*/
proto.Soit.Authentication.QueryRoleReply.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Soit.Authentication.FindRoleReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.FindRoleReply}
 */
proto.Soit.Authentication.QueryRoleReply.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Soit.Authentication.FindRoleReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.QueryRoleReply} returns this
 */
proto.Soit.Authentication.QueryRoleReply.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.QueryRoleRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.QueryRoleRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.QueryRoleRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    contains: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orderRequest: (f = msg.getOrderRequest()) && protobuf_infrastructure_pb.OrderRequest.toObject(includeInstance, f),
    pageRequest: (f = msg.getPageRequest()) && protobuf_infrastructure_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.QueryRoleRequest}
 */
proto.Soit.Authentication.QueryRoleRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.QueryRoleRequest;
  return proto.Soit.Authentication.QueryRoleRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.QueryRoleRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.QueryRoleRequest}
 */
proto.Soit.Authentication.QueryRoleRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setContains(value);
      break;
    case 2:
      var value = new protobuf_infrastructure_pb.OrderRequest;
      reader.readMessage(value,protobuf_infrastructure_pb.OrderRequest.deserializeBinaryFromReader);
      msg.setOrderRequest(value);
      break;
    case 3:
      var value = new protobuf_infrastructure_pb.PageRequest;
      reader.readMessage(value,protobuf_infrastructure_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPageRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.QueryRoleRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.QueryRoleRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.QueryRoleRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContains();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrderRequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      protobuf_infrastructure_pb.OrderRequest.serializeBinaryToWriter
    );
  }
  f = message.getPageRequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      protobuf_infrastructure_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string contains = 1;
 * @return {string}
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.getContains = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.QueryRoleRequest} returns this
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.setContains = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Soit.Infrastructure.OrderRequest order_request = 2;
 * @return {?proto.Soit.Infrastructure.OrderRequest}
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.getOrderRequest = function() {
  return /** @type{?proto.Soit.Infrastructure.OrderRequest} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.OrderRequest, 2));
};


/**
 * @param {?proto.Soit.Infrastructure.OrderRequest|undefined} value
 * @return {!proto.Soit.Authentication.QueryRoleRequest} returns this
*/
proto.Soit.Authentication.QueryRoleRequest.prototype.setOrderRequest = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.Authentication.QueryRoleRequest} returns this
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.clearOrderRequest = function() {
  return this.setOrderRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.hasOrderRequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Soit.Infrastructure.PageRequest page_request = 3;
 * @return {?proto.Soit.Infrastructure.PageRequest}
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.getPageRequest = function() {
  return /** @type{?proto.Soit.Infrastructure.PageRequest} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.PageRequest, 3));
};


/**
 * @param {?proto.Soit.Infrastructure.PageRequest|undefined} value
 * @return {!proto.Soit.Authentication.QueryRoleRequest} returns this
*/
proto.Soit.Authentication.QueryRoleRequest.prototype.setPageRequest = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.Authentication.QueryRoleRequest} returns this
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.clearPageRequest = function() {
  return this.setPageRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.Authentication.QueryRoleRequest.prototype.hasPageRequest = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.repeatedFields_ = [2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdateRoleComponentsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdateRoleComponentsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    moduleIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    pageIdsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    elementIdsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest}
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdateRoleComponentsRequest;
  return proto.Soit.Authentication.UpdateRoleComponentsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdateRoleComponentsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest}
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addModuleIds(values[i]);
      }
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPageIds(values[i]);
      }
      break;
    case 4:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addElementIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdateRoleComponentsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdateRoleComponentsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getModuleIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      2,
      f
    );
  }
  f = message.getPageIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      3,
      f
    );
  }
  f = message.getElementIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      4,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated int64 module_ids = 2;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.getModuleIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.setModuleIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.addModuleIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.clearModuleIdsList = function() {
  return this.setModuleIdsList([]);
};


/**
 * repeated int64 page_ids = 3;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.getPageIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.setPageIdsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.addPageIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.clearPageIdsList = function() {
  return this.setPageIdsList([]);
};


/**
 * repeated int64 element_ids = 4;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.getElementIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.setElementIdsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.addElementIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateRoleComponentsRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleComponentsRequest.prototype.clearElementIdsList = function() {
  return this.setElementIdsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdateRoleRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdateRoleRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateRoleRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    state: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdateRoleRequest}
 */
proto.Soit.Authentication.UpdateRoleRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdateRoleRequest;
  return proto.Soit.Authentication.UpdateRoleRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdateRoleRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdateRoleRequest}
 */
proto.Soit.Authentication.UpdateRoleRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {!proto.Soit.Infrastructure.EntityStates} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdateRoleRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdateRoleRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateRoleRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdateRoleRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdateRoleRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdateRoleRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional Soit.Infrastructure.EntityStates state = 4;
 * @return {!proto.Soit.Infrastructure.EntityStates}
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.getState = function() {
  return /** @type {!proto.Soit.Infrastructure.EntityStates} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.EntityStates} value
 * @return {!proto.Soit.Authentication.UpdateRoleRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdateRoleStatesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdateRoleStatesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    idsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    state: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdateRoleStatesRequest}
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdateRoleStatesRequest;
  return proto.Soit.Authentication.UpdateRoleStatesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdateRoleStatesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdateRoleStatesRequest}
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addIds(values[i]);
      }
      break;
    case 2:
      var value = /** @type {!proto.Soit.Infrastructure.EntityStates} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdateRoleStatesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdateRoleStatesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * repeated int64 ids = 1;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.prototype.getIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateRoleStatesRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.prototype.setIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateRoleStatesRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.prototype.addIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateRoleStatesRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.prototype.clearIdsList = function() {
  return this.setIdsList([]);
};


/**
 * optional Soit.Infrastructure.EntityStates state = 2;
 * @return {!proto.Soit.Infrastructure.EntityStates}
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.prototype.getState = function() {
  return /** @type {!proto.Soit.Infrastructure.EntityStates} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.EntityStates} value
 * @return {!proto.Soit.Authentication.UpdateRoleStatesRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleStatesRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdateRoleUsersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdateRoleUsersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    userIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdateRoleUsersRequest}
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdateRoleUsersRequest;
  return proto.Soit.Authentication.UpdateRoleUsersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdateRoleUsersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdateRoleUsersRequest}
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addUserIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdateRoleUsersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdateRoleUsersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getUserIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdateRoleUsersRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated int64 user_ids = 2;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.prototype.getUserIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateRoleUsersRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.prototype.setUserIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateRoleUsersRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.prototype.addUserIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateRoleUsersRequest} returns this
 */
proto.Soit.Authentication.UpdateRoleUsersRequest.prototype.clearUserIdsList = function() {
  return this.setUserIdsList([]);
};


goog.object.extend(exports, proto.Soit.Authentication);
