// source: protos/Authentication/user.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var protobuf_infrastructure_pb = require('../../protobuf/infrastructure_pb.js');
goog.object.extend(proto, protobuf_infrastructure_pb);
goog.exportSymbol('proto.Soit.Authentication.AllowNameRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.CreateUserRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.FindUserReply', null, global);
goog.exportSymbol('proto.Soit.Authentication.QueryUserReply', null, global);
goog.exportSymbol('proto.Soit.Authentication.QueryUserRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdatePasswordRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdateUserOrganizationsRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdateUserRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdateUserRolesRequest', null, global);
goog.exportSymbol('proto.Soit.Authentication.UpdateUserStatesRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.CreateUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.CreateUserRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.CreateUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.CreateUserRequest.displayName = 'proto.Soit.Authentication.CreateUserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.FindUserReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.FindUserReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.FindUserReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.FindUserReply.displayName = 'proto.Soit.Authentication.FindUserReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.QueryUserReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.QueryUserReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.QueryUserReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.QueryUserReply.displayName = 'proto.Soit.Authentication.QueryUserReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.QueryUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.QueryUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.QueryUserRequest.displayName = 'proto.Soit.Authentication.QueryUserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdatePasswordRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.UpdatePasswordRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdatePasswordRequest.displayName = 'proto.Soit.Authentication.UpdatePasswordRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.UpdateUserOrganizationsRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.UpdateUserOrganizationsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdateUserOrganizationsRequest.displayName = 'proto.Soit.Authentication.UpdateUserOrganizationsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdateUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.UpdateUserRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.UpdateUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdateUserRequest.displayName = 'proto.Soit.Authentication.UpdateUserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdateUserRolesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.UpdateUserRolesRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.UpdateUserRolesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdateUserRolesRequest.displayName = 'proto.Soit.Authentication.UpdateUserRolesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.UpdateUserStatesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.Authentication.UpdateUserStatesRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.Authentication.UpdateUserStatesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.UpdateUserStatesRequest.displayName = 'proto.Soit.Authentication.UpdateUserStatesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.Authentication.AllowNameRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.Authentication.AllowNameRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.Authentication.AllowNameRequest.displayName = 'proto.Soit.Authentication.AllowNameRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.CreateUserRequest.repeatedFields_ = [10,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.CreateUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.CreateUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.CreateUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cipher: jspb.Message.getFieldWithDefault(msg, 2, ""),
    legalName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    mobile: jspb.Message.getFieldWithDefault(msg, 5, ""),
    phone: jspb.Message.getFieldWithDefault(msg, 6, ""),
    email: jspb.Message.getFieldWithDefault(msg, 7, ""),
    photo: jspb.Message.getFieldWithDefault(msg, 8, ""),
    state: jspb.Message.getFieldWithDefault(msg, 9, 0),
    organizationIdsList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    roleIdsList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.CreateUserRequest}
 */
proto.Soit.Authentication.CreateUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.CreateUserRequest;
  return proto.Soit.Authentication.CreateUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.CreateUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.CreateUserRequest}
 */
proto.Soit.Authentication.CreateUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCipher(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLegalName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMobile(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhone(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoto(value);
      break;
    case 9:
      var value = /** @type {!proto.Soit.Infrastructure.EntityStates} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 10:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addOrganizationIds(values[i]);
      }
      break;
    case 11:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRoleIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.CreateUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.CreateUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.CreateUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCipher();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLegalName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMobile();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPhone();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPhoto();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getOrganizationIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      10,
      f
    );
  }
  f = message.getRoleIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      11,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string cipher = 2;
 * @return {string}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getCipher = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setCipher = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string legal_name = 3;
 * @return {string}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getLegalName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setLegalName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string mobile = 5;
 * @return {string}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getMobile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setMobile = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string phone = 6;
 * @return {string}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string email = 7;
 * @return {string}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string photo = 8;
 * @return {string}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getPhoto = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setPhoto = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional Soit.Infrastructure.EntityStates state = 9;
 * @return {!proto.Soit.Infrastructure.EntityStates}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getState = function() {
  return /** @type {!proto.Soit.Infrastructure.EntityStates} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.EntityStates} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * repeated int64 organization_ids = 10;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getOrganizationIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setOrganizationIdsList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.addOrganizationIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.clearOrganizationIdsList = function() {
  return this.setOrganizationIdsList([]);
};


/**
 * repeated int64 role_ids = 11;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.CreateUserRequest.prototype.getRoleIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.setRoleIdsList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.addRoleIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.CreateUserRequest} returns this
 */
proto.Soit.Authentication.CreateUserRequest.prototype.clearRoleIdsList = function() {
  return this.setRoleIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.FindUserReply.repeatedFields_ = [11,12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.FindUserReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.FindUserReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.FindUserReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindUserReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    cipher: jspb.Message.getFieldWithDefault(msg, 3, ""),
    legalName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    mobile: jspb.Message.getFieldWithDefault(msg, 6, ""),
    phone: jspb.Message.getFieldWithDefault(msg, 7, ""),
    email: jspb.Message.getFieldWithDefault(msg, 8, ""),
    photo: jspb.Message.getFieldWithDefault(msg, 9, ""),
    state: jspb.Message.getFieldWithDefault(msg, 10, 0),
    organizationsList: jspb.Message.toObjectList(msg.getOrganizationsList(),
    protobuf_infrastructure_pb.NamedIdentify.toObject, includeInstance),
    rolesList: jspb.Message.toObjectList(msg.getRolesList(),
    protobuf_infrastructure_pb.NamedIdentify.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.FindUserReply}
 */
proto.Soit.Authentication.FindUserReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.FindUserReply;
  return proto.Soit.Authentication.FindUserReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.FindUserReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.FindUserReply}
 */
proto.Soit.Authentication.FindUserReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCipher(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLegalName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMobile(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhone(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoto(value);
      break;
    case 10:
      var value = /** @type {!proto.Soit.Infrastructure.EntityStates} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 11:
      var value = new protobuf_infrastructure_pb.NamedIdentify;
      reader.readMessage(value,protobuf_infrastructure_pb.NamedIdentify.deserializeBinaryFromReader);
      msg.addOrganizations(value);
      break;
    case 12:
      var value = new protobuf_infrastructure_pb.NamedIdentify;
      reader.readMessage(value,protobuf_infrastructure_pb.NamedIdentify.deserializeBinaryFromReader);
      msg.addRoles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.FindUserReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.FindUserReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.FindUserReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.FindUserReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCipher();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLegalName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMobile();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPhone();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPhoto();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
  f = message.getOrganizationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      protobuf_infrastructure_pb.NamedIdentify.serializeBinaryToWriter
    );
  }
  f = message.getRolesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      protobuf_infrastructure_pb.NamedIdentify.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.FindUserReply.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Soit.Authentication.FindUserReply.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string cipher = 3;
 * @return {string}
 */
proto.Soit.Authentication.FindUserReply.prototype.getCipher = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setCipher = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string legal_name = 4;
 * @return {string}
 */
proto.Soit.Authentication.FindUserReply.prototype.getLegalName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setLegalName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.Soit.Authentication.FindUserReply.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string mobile = 6;
 * @return {string}
 */
proto.Soit.Authentication.FindUserReply.prototype.getMobile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setMobile = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string phone = 7;
 * @return {string}
 */
proto.Soit.Authentication.FindUserReply.prototype.getPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string email = 8;
 * @return {string}
 */
proto.Soit.Authentication.FindUserReply.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string photo = 9;
 * @return {string}
 */
proto.Soit.Authentication.FindUserReply.prototype.getPhoto = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setPhoto = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional Soit.Infrastructure.EntityStates state = 10;
 * @return {!proto.Soit.Infrastructure.EntityStates}
 */
proto.Soit.Authentication.FindUserReply.prototype.getState = function() {
  return /** @type {!proto.Soit.Infrastructure.EntityStates} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.EntityStates} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};


/**
 * repeated Soit.Infrastructure.NamedIdentify organizations = 11;
 * @return {!Array<!proto.Soit.Infrastructure.NamedIdentify>}
 */
proto.Soit.Authentication.FindUserReply.prototype.getOrganizationsList = function() {
  return /** @type{!Array<!proto.Soit.Infrastructure.NamedIdentify>} */ (
    jspb.Message.getRepeatedWrapperField(this, protobuf_infrastructure_pb.NamedIdentify, 11));
};


/**
 * @param {!Array<!proto.Soit.Infrastructure.NamedIdentify>} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
*/
proto.Soit.Authentication.FindUserReply.prototype.setOrganizationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.Soit.Infrastructure.NamedIdentify=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.Infrastructure.NamedIdentify}
 */
proto.Soit.Authentication.FindUserReply.prototype.addOrganizations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.Soit.Infrastructure.NamedIdentify, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.clearOrganizationsList = function() {
  return this.setOrganizationsList([]);
};


/**
 * repeated Soit.Infrastructure.NamedIdentify roles = 12;
 * @return {!Array<!proto.Soit.Infrastructure.NamedIdentify>}
 */
proto.Soit.Authentication.FindUserReply.prototype.getRolesList = function() {
  return /** @type{!Array<!proto.Soit.Infrastructure.NamedIdentify>} */ (
    jspb.Message.getRepeatedWrapperField(this, protobuf_infrastructure_pb.NamedIdentify, 12));
};


/**
 * @param {!Array<!proto.Soit.Infrastructure.NamedIdentify>} value
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
*/
proto.Soit.Authentication.FindUserReply.prototype.setRolesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.Soit.Infrastructure.NamedIdentify=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.Infrastructure.NamedIdentify}
 */
proto.Soit.Authentication.FindUserReply.prototype.addRoles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.Soit.Infrastructure.NamedIdentify, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.FindUserReply} returns this
 */
proto.Soit.Authentication.FindUserReply.prototype.clearRolesList = function() {
  return this.setRolesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.QueryUserReply.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.QueryUserReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.QueryUserReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.QueryUserReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.QueryUserReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageResult: (f = msg.getPageResult()) && protobuf_infrastructure_pb.PageResult.toObject(includeInstance, f),
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.Soit.Authentication.FindUserReply.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.QueryUserReply}
 */
proto.Soit.Authentication.QueryUserReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.QueryUserReply;
  return proto.Soit.Authentication.QueryUserReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.QueryUserReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.QueryUserReply}
 */
proto.Soit.Authentication.QueryUserReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protobuf_infrastructure_pb.PageResult;
      reader.readMessage(value,protobuf_infrastructure_pb.PageResult.deserializeBinaryFromReader);
      msg.setPageResult(value);
      break;
    case 2:
      var value = new proto.Soit.Authentication.FindUserReply;
      reader.readMessage(value,proto.Soit.Authentication.FindUserReply.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.QueryUserReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.QueryUserReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.QueryUserReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.QueryUserReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageResult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protobuf_infrastructure_pb.PageResult.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Soit.Authentication.FindUserReply.serializeBinaryToWriter
    );
  }
};


/**
 * optional Soit.Infrastructure.PageResult page_result = 1;
 * @return {?proto.Soit.Infrastructure.PageResult}
 */
proto.Soit.Authentication.QueryUserReply.prototype.getPageResult = function() {
  return /** @type{?proto.Soit.Infrastructure.PageResult} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.PageResult, 1));
};


/**
 * @param {?proto.Soit.Infrastructure.PageResult|undefined} value
 * @return {!proto.Soit.Authentication.QueryUserReply} returns this
*/
proto.Soit.Authentication.QueryUserReply.prototype.setPageResult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.Authentication.QueryUserReply} returns this
 */
proto.Soit.Authentication.QueryUserReply.prototype.clearPageResult = function() {
  return this.setPageResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.Authentication.QueryUserReply.prototype.hasPageResult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated FindUserReply items = 2;
 * @return {!Array<!proto.Soit.Authentication.FindUserReply>}
 */
proto.Soit.Authentication.QueryUserReply.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.Soit.Authentication.FindUserReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Soit.Authentication.FindUserReply, 2));
};


/**
 * @param {!Array<!proto.Soit.Authentication.FindUserReply>} value
 * @return {!proto.Soit.Authentication.QueryUserReply} returns this
*/
proto.Soit.Authentication.QueryUserReply.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Soit.Authentication.FindUserReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.FindUserReply}
 */
proto.Soit.Authentication.QueryUserReply.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Soit.Authentication.FindUserReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.QueryUserReply} returns this
 */
proto.Soit.Authentication.QueryUserReply.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.QueryUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.QueryUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.QueryUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.QueryUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    contains: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orderRequest: (f = msg.getOrderRequest()) && protobuf_infrastructure_pb.OrderRequest.toObject(includeInstance, f),
    pageRequest: (f = msg.getPageRequest()) && protobuf_infrastructure_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.QueryUserRequest}
 */
proto.Soit.Authentication.QueryUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.QueryUserRequest;
  return proto.Soit.Authentication.QueryUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.QueryUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.QueryUserRequest}
 */
proto.Soit.Authentication.QueryUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setContains(value);
      break;
    case 2:
      var value = new protobuf_infrastructure_pb.OrderRequest;
      reader.readMessage(value,protobuf_infrastructure_pb.OrderRequest.deserializeBinaryFromReader);
      msg.setOrderRequest(value);
      break;
    case 3:
      var value = new protobuf_infrastructure_pb.PageRequest;
      reader.readMessage(value,protobuf_infrastructure_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPageRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.QueryUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.QueryUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.QueryUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.QueryUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContains();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrderRequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      protobuf_infrastructure_pb.OrderRequest.serializeBinaryToWriter
    );
  }
  f = message.getPageRequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      protobuf_infrastructure_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string contains = 1;
 * @return {string}
 */
proto.Soit.Authentication.QueryUserRequest.prototype.getContains = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.QueryUserRequest} returns this
 */
proto.Soit.Authentication.QueryUserRequest.prototype.setContains = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Soit.Infrastructure.OrderRequest order_request = 2;
 * @return {?proto.Soit.Infrastructure.OrderRequest}
 */
proto.Soit.Authentication.QueryUserRequest.prototype.getOrderRequest = function() {
  return /** @type{?proto.Soit.Infrastructure.OrderRequest} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.OrderRequest, 2));
};


/**
 * @param {?proto.Soit.Infrastructure.OrderRequest|undefined} value
 * @return {!proto.Soit.Authentication.QueryUserRequest} returns this
*/
proto.Soit.Authentication.QueryUserRequest.prototype.setOrderRequest = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.Authentication.QueryUserRequest} returns this
 */
proto.Soit.Authentication.QueryUserRequest.prototype.clearOrderRequest = function() {
  return this.setOrderRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.Authentication.QueryUserRequest.prototype.hasOrderRequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Soit.Infrastructure.PageRequest page_request = 3;
 * @return {?proto.Soit.Infrastructure.PageRequest}
 */
proto.Soit.Authentication.QueryUserRequest.prototype.getPageRequest = function() {
  return /** @type{?proto.Soit.Infrastructure.PageRequest} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.PageRequest, 3));
};


/**
 * @param {?proto.Soit.Infrastructure.PageRequest|undefined} value
 * @return {!proto.Soit.Authentication.QueryUserRequest} returns this
*/
proto.Soit.Authentication.QueryUserRequest.prototype.setPageRequest = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.Authentication.QueryUserRequest} returns this
 */
proto.Soit.Authentication.QueryUserRequest.prototype.clearPageRequest = function() {
  return this.setPageRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.Authentication.QueryUserRequest.prototype.hasPageRequest = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdatePasswordRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdatePasswordRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdatePasswordRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdatePasswordRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    oldCipher: jspb.Message.getFieldWithDefault(msg, 1, ""),
    newCipher: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdatePasswordRequest}
 */
proto.Soit.Authentication.UpdatePasswordRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdatePasswordRequest;
  return proto.Soit.Authentication.UpdatePasswordRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdatePasswordRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdatePasswordRequest}
 */
proto.Soit.Authentication.UpdatePasswordRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOldCipher(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNewCipher(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdatePasswordRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdatePasswordRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdatePasswordRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdatePasswordRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOldCipher();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNewCipher();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string old_cipher = 1;
 * @return {string}
 */
proto.Soit.Authentication.UpdatePasswordRequest.prototype.getOldCipher = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdatePasswordRequest} returns this
 */
proto.Soit.Authentication.UpdatePasswordRequest.prototype.setOldCipher = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string new_cipher = 2;
 * @return {string}
 */
proto.Soit.Authentication.UpdatePasswordRequest.prototype.getNewCipher = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdatePasswordRequest} returns this
 */
proto.Soit.Authentication.UpdatePasswordRequest.prototype.setNewCipher = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdateUserOrganizationsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdateUserOrganizationsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    organizationIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdateUserOrganizationsRequest}
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdateUserOrganizationsRequest;
  return proto.Soit.Authentication.UpdateUserOrganizationsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdateUserOrganizationsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdateUserOrganizationsRequest}
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addOrganizationIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdateUserOrganizationsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdateUserOrganizationsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getOrganizationIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdateUserOrganizationsRequest} returns this
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated int64 organization_ids = 2;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.prototype.getOrganizationIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateUserOrganizationsRequest} returns this
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.prototype.setOrganizationIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateUserOrganizationsRequest} returns this
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.prototype.addOrganizationIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateUserOrganizationsRequest} returns this
 */
proto.Soit.Authentication.UpdateUserOrganizationsRequest.prototype.clearOrganizationIdsList = function() {
  return this.setOrganizationIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.UpdateUserRequest.repeatedFields_ = [9,10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdateUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdateUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    legalName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    mobile: jspb.Message.getFieldWithDefault(msg, 4, ""),
    phone: jspb.Message.getFieldWithDefault(msg, 5, ""),
    email: jspb.Message.getFieldWithDefault(msg, 6, ""),
    photo: jspb.Message.getFieldWithDefault(msg, 7, ""),
    state: jspb.Message.getFieldWithDefault(msg, 8, 0),
    organizationIdsList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    roleIdsList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdateUserRequest}
 */
proto.Soit.Authentication.UpdateUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdateUserRequest;
  return proto.Soit.Authentication.UpdateUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdateUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdateUserRequest}
 */
proto.Soit.Authentication.UpdateUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLegalName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMobile(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhone(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoto(value);
      break;
    case 8:
      var value = /** @type {!proto.Soit.Infrastructure.EntityStates} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 9:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addOrganizationIds(values[i]);
      }
      break;
    case 10:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRoleIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdateUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdateUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getLegalName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMobile();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPhone();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPhoto();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getOrganizationIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      9,
      f
    );
  }
  f = message.getRoleIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      10,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string legal_name = 2;
 * @return {string}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getLegalName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setLegalName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string mobile = 4;
 * @return {string}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getMobile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setMobile = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string phone = 5;
 * @return {string}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string email = 6;
 * @return {string}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string photo = 7;
 * @return {string}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getPhoto = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setPhoto = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional Soit.Infrastructure.EntityStates state = 8;
 * @return {!proto.Soit.Infrastructure.EntityStates}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getState = function() {
  return /** @type {!proto.Soit.Infrastructure.EntityStates} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.EntityStates} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * repeated int64 organization_ids = 9;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getOrganizationIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setOrganizationIdsList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.addOrganizationIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.clearOrganizationIdsList = function() {
  return this.setOrganizationIdsList([]);
};


/**
 * repeated int64 role_ids = 10;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.getRoleIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.setRoleIdsList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.addRoleIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateUserRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRequest.prototype.clearRoleIdsList = function() {
  return this.setRoleIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.UpdateUserRolesRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdateUserRolesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdateUserRolesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdateUserRolesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateUserRolesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    roleIdsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdateUserRolesRequest}
 */
proto.Soit.Authentication.UpdateUserRolesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdateUserRolesRequest;
  return proto.Soit.Authentication.UpdateUserRolesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdateUserRolesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdateUserRolesRequest}
 */
proto.Soit.Authentication.UpdateUserRolesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addRoleIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdateUserRolesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdateUserRolesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdateUserRolesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateUserRolesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getRoleIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.Authentication.UpdateUserRolesRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.Authentication.UpdateUserRolesRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRolesRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated int64 role_ids = 2;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateUserRolesRequest.prototype.getRoleIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateUserRolesRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRolesRequest.prototype.setRoleIdsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateUserRolesRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRolesRequest.prototype.addRoleIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateUserRolesRequest} returns this
 */
proto.Soit.Authentication.UpdateUserRolesRequest.prototype.clearRoleIdsList = function() {
  return this.setRoleIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.Authentication.UpdateUserStatesRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.UpdateUserStatesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.UpdateUserStatesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.UpdateUserStatesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateUserStatesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    idsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    state: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.UpdateUserStatesRequest}
 */
proto.Soit.Authentication.UpdateUserStatesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.UpdateUserStatesRequest;
  return proto.Soit.Authentication.UpdateUserStatesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.UpdateUserStatesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.UpdateUserStatesRequest}
 */
proto.Soit.Authentication.UpdateUserStatesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addIds(values[i]);
      }
      break;
    case 2:
      var value = /** @type {!proto.Soit.Infrastructure.EntityStates} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.UpdateUserStatesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.UpdateUserStatesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.UpdateUserStatesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.UpdateUserStatesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * repeated int64 ids = 1;
 * @return {!Array<number>}
 */
proto.Soit.Authentication.UpdateUserStatesRequest.prototype.getIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.Authentication.UpdateUserStatesRequest} returns this
 */
proto.Soit.Authentication.UpdateUserStatesRequest.prototype.setIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.Authentication.UpdateUserStatesRequest} returns this
 */
proto.Soit.Authentication.UpdateUserStatesRequest.prototype.addIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.Authentication.UpdateUserStatesRequest} returns this
 */
proto.Soit.Authentication.UpdateUserStatesRequest.prototype.clearIdsList = function() {
  return this.setIdsList([]);
};


/**
 * optional Soit.Infrastructure.EntityStates state = 2;
 * @return {!proto.Soit.Infrastructure.EntityStates}
 */
proto.Soit.Authentication.UpdateUserStatesRequest.prototype.getState = function() {
  return /** @type {!proto.Soit.Infrastructure.EntityStates} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.Soit.Infrastructure.EntityStates} value
 * @return {!proto.Soit.Authentication.UpdateUserStatesRequest} returns this
 */
proto.Soit.Authentication.UpdateUserStatesRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.Authentication.AllowNameRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.Authentication.AllowNameRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.Authentication.AllowNameRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.AllowNameRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.Authentication.AllowNameRequest}
 */
proto.Soit.Authentication.AllowNameRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.Authentication.AllowNameRequest;
  return proto.Soit.Authentication.AllowNameRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.Authentication.AllowNameRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.Authentication.AllowNameRequest}
 */
proto.Soit.Authentication.AllowNameRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.Authentication.AllowNameRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.Authentication.AllowNameRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.Authentication.AllowNameRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.Authentication.AllowNameRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Soit.Authentication.AllowNameRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.Authentication.AllowNameRequest} returns this
 */
proto.Soit.Authentication.AllowNameRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.Soit.Authentication);
