// source: protos/equipment.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var protobuf_infrastructure_pb = require('../protobuf/infrastructure_pb.js');
goog.object.extend(proto, protobuf_infrastructure_pb);
goog.exportSymbol('proto.Soit.System.CreateEquipmentRequest', null, global);
goog.exportSymbol('proto.Soit.System.FindEquipmentReply', null, global);
goog.exportSymbol('proto.Soit.System.QueryEquipmentReply', null, global);
goog.exportSymbol('proto.Soit.System.QueryEquipmentRequest', null, global);
goog.exportSymbol('proto.Soit.System.State', null, global);
goog.exportSymbol('proto.Soit.System.UpdateEquipmentRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.CreateEquipmentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.System.CreateEquipmentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.CreateEquipmentRequest.displayName = 'proto.Soit.System.CreateEquipmentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.UpdateEquipmentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.System.UpdateEquipmentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.UpdateEquipmentRequest.displayName = 'proto.Soit.System.UpdateEquipmentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.FindEquipmentReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.System.FindEquipmentReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.FindEquipmentReply.displayName = 'proto.Soit.System.FindEquipmentReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.QueryEquipmentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.System.QueryEquipmentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.QueryEquipmentRequest.displayName = 'proto.Soit.System.QueryEquipmentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.QueryEquipmentReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.System.QueryEquipmentReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.System.QueryEquipmentReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.QueryEquipmentReply.displayName = 'proto.Soit.System.QueryEquipmentReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.CreateEquipmentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.CreateEquipmentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.CreateEquipmentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    number: jspb.Message.getFieldWithDefault(msg, 2, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 3, ""),
    modelName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    memory: jspb.Message.getFieldWithDefault(msg, 5, ""),
    purchaseDate: jspb.Message.getFieldWithDefault(msg, 6, 0),
    eliminateDate: jspb.Message.getFieldWithDefault(msg, 7, 0),
    state: jspb.Message.getFieldWithDefault(msg, 8, 0),
    userId: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.CreateEquipmentRequest}
 */
proto.Soit.System.CreateEquipmentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.CreateEquipmentRequest;
  return proto.Soit.System.CreateEquipmentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.CreateEquipmentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.CreateEquipmentRequest}
 */
proto.Soit.System.CreateEquipmentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumber(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemory(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPurchaseDate(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEliminateDate(value);
      break;
    case 8:
      var value = /** @type {!proto.Soit.System.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.CreateEquipmentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.CreateEquipmentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.CreateEquipmentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getModelName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMemory();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPurchaseDate();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getEliminateDate();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string number = 2;
 * @return {string}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string brand = 3;
 * @return {string}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string model_name = 4;
 * @return {string}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getModelName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setModelName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string memory = 5;
 * @return {string}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getMemory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setMemory = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int64 Purchase_date = 6;
 * @return {number}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getPurchaseDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setPurchaseDate = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 Eliminate_date = 7;
 * @return {number}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getEliminateDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setEliminateDate = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional State state = 8;
 * @return {!proto.Soit.System.State}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getState = function() {
  return /** @type {!proto.Soit.System.State} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.Soit.System.State} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};


/**
 * optional int64 user_id = 9;
 * @return {number}
 */
proto.Soit.System.CreateEquipmentRequest.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.CreateEquipmentRequest} returns this
 */
proto.Soit.System.CreateEquipmentRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.UpdateEquipmentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.UpdateEquipmentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.UpdateEquipmentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    type: jspb.Message.getFieldWithDefault(msg, 2, ""),
    number: jspb.Message.getFieldWithDefault(msg, 3, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 4, ""),
    modelName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    memory: jspb.Message.getFieldWithDefault(msg, 6, ""),
    purchaseDate: jspb.Message.getFieldWithDefault(msg, 7, 0),
    eliminateDate: jspb.Message.getFieldWithDefault(msg, 8, 0),
    state: jspb.Message.getFieldWithDefault(msg, 9, 0),
    userId: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.UpdateEquipmentRequest}
 */
proto.Soit.System.UpdateEquipmentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.UpdateEquipmentRequest;
  return proto.Soit.System.UpdateEquipmentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.UpdateEquipmentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.UpdateEquipmentRequest}
 */
proto.Soit.System.UpdateEquipmentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumber(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemory(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPurchaseDate(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEliminateDate(value);
      break;
    case 9:
      var value = /** @type {!proto.Soit.System.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.UpdateEquipmentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.UpdateEquipmentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.UpdateEquipmentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNumber();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getModelName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMemory();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPurchaseDate();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getEliminateDate();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string number = 3;
 * @return {string}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string brand = 4;
 * @return {string}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string model_name = 5;
 * @return {string}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getModelName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setModelName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string memory = 6;
 * @return {string}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getMemory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setMemory = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 Purchase_date = 7;
 * @return {number}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getPurchaseDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setPurchaseDate = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 Eliminate_date = 8;
 * @return {number}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getEliminateDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setEliminateDate = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional State state = 9;
 * @return {!proto.Soit.System.State}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getState = function() {
  return /** @type {!proto.Soit.System.State} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.Soit.System.State} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional int64 user_id = 10;
 * @return {number}
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.UpdateEquipmentRequest} returns this
 */
proto.Soit.System.UpdateEquipmentRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.FindEquipmentReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.FindEquipmentReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.FindEquipmentReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.FindEquipmentReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    type: jspb.Message.getFieldWithDefault(msg, 2, ""),
    number: jspb.Message.getFieldWithDefault(msg, 3, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 4, ""),
    modelName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    memory: jspb.Message.getFieldWithDefault(msg, 6, ""),
    purchaseDate: jspb.Message.getFieldWithDefault(msg, 7, 0),
    eliminateDate: jspb.Message.getFieldWithDefault(msg, 8, 0),
    state: jspb.Message.getFieldWithDefault(msg, 9, 0),
    userId: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.FindEquipmentReply}
 */
proto.Soit.System.FindEquipmentReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.FindEquipmentReply;
  return proto.Soit.System.FindEquipmentReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.FindEquipmentReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.FindEquipmentReply}
 */
proto.Soit.System.FindEquipmentReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setNumber(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setModelName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemory(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPurchaseDate(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEliminateDate(value);
      break;
    case 9:
      var value = /** @type {!proto.Soit.System.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.FindEquipmentReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.FindEquipmentReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.FindEquipmentReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.FindEquipmentReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getNumber();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getModelName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMemory();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPurchaseDate();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getEliminateDate();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getUserId();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.System.FindEquipmentReply.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string type = 2;
 * @return {string}
 */
proto.Soit.System.FindEquipmentReply.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string number = 3;
 * @return {string}
 */
proto.Soit.System.FindEquipmentReply.prototype.getNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string brand = 4;
 * @return {string}
 */
proto.Soit.System.FindEquipmentReply.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string model_name = 5;
 * @return {string}
 */
proto.Soit.System.FindEquipmentReply.prototype.getModelName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setModelName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string memory = 6;
 * @return {string}
 */
proto.Soit.System.FindEquipmentReply.prototype.getMemory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setMemory = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int64 Purchase_date = 7;
 * @return {number}
 */
proto.Soit.System.FindEquipmentReply.prototype.getPurchaseDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setPurchaseDate = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 Eliminate_date = 8;
 * @return {number}
 */
proto.Soit.System.FindEquipmentReply.prototype.getEliminateDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setEliminateDate = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional State state = 9;
 * @return {!proto.Soit.System.State}
 */
proto.Soit.System.FindEquipmentReply.prototype.getState = function() {
  return /** @type {!proto.Soit.System.State} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.Soit.System.State} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional int64 user_id = 10;
 * @return {number}
 */
proto.Soit.System.FindEquipmentReply.prototype.getUserId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.FindEquipmentReply} returns this
 */
proto.Soit.System.FindEquipmentReply.prototype.setUserId = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.QueryEquipmentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.QueryEquipmentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.QueryEquipmentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.QueryEquipmentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    contains: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orderRequest: (f = msg.getOrderRequest()) && protobuf_infrastructure_pb.OrderRequest.toObject(includeInstance, f),
    pageRequest: (f = msg.getPageRequest()) && protobuf_infrastructure_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.QueryEquipmentRequest}
 */
proto.Soit.System.QueryEquipmentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.QueryEquipmentRequest;
  return proto.Soit.System.QueryEquipmentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.QueryEquipmentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.QueryEquipmentRequest}
 */
proto.Soit.System.QueryEquipmentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setContains(value);
      break;
    case 2:
      var value = new protobuf_infrastructure_pb.OrderRequest;
      reader.readMessage(value,protobuf_infrastructure_pb.OrderRequest.deserializeBinaryFromReader);
      msg.setOrderRequest(value);
      break;
    case 3:
      var value = new protobuf_infrastructure_pb.PageRequest;
      reader.readMessage(value,protobuf_infrastructure_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPageRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.QueryEquipmentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.QueryEquipmentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.QueryEquipmentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.QueryEquipmentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContains();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrderRequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      protobuf_infrastructure_pb.OrderRequest.serializeBinaryToWriter
    );
  }
  f = message.getPageRequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      protobuf_infrastructure_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string contains = 1;
 * @return {string}
 */
proto.Soit.System.QueryEquipmentRequest.prototype.getContains = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.QueryEquipmentRequest} returns this
 */
proto.Soit.System.QueryEquipmentRequest.prototype.setContains = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional OrderRequest order_request = 2;
 * @return {?proto.Soit.System.OrderRequest}
 */
proto.Soit.System.QueryEquipmentRequest.prototype.getOrderRequest = function() {
  return /** @type{?proto.Soit.System.OrderRequest} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.OrderRequest, 2));
};


/**
 * @param {?proto.Soit.System.OrderRequest|undefined} value
 * @return {!proto.Soit.System.QueryEquipmentRequest} returns this
*/
proto.Soit.System.QueryEquipmentRequest.prototype.setOrderRequest = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.System.QueryEquipmentRequest} returns this
 */
proto.Soit.System.QueryEquipmentRequest.prototype.clearOrderRequest = function() {
  return this.setOrderRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.System.QueryEquipmentRequest.prototype.hasOrderRequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PageRequest page_request = 3;
 * @return {?proto.Soit.System.PageRequest}
 */
proto.Soit.System.QueryEquipmentRequest.prototype.getPageRequest = function() {
  return /** @type{?proto.Soit.System.PageRequest} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.PageRequest, 3));
};


/**
 * @param {?proto.Soit.System.PageRequest|undefined} value
 * @return {!proto.Soit.System.QueryEquipmentRequest} returns this
*/
proto.Soit.System.QueryEquipmentRequest.prototype.setPageRequest = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.System.QueryEquipmentRequest} returns this
 */
proto.Soit.System.QueryEquipmentRequest.prototype.clearPageRequest = function() {
  return this.setPageRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.System.QueryEquipmentRequest.prototype.hasPageRequest = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.System.QueryEquipmentReply.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.QueryEquipmentReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.QueryEquipmentReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.QueryEquipmentReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.QueryEquipmentReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageResult: (f = msg.getPageResult()) && protobuf_infrastructure_pb.PageResult.toObject(includeInstance, f),
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.Soit.System.FindEquipmentReply.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.QueryEquipmentReply}
 */
proto.Soit.System.QueryEquipmentReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.QueryEquipmentReply;
  return proto.Soit.System.QueryEquipmentReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.QueryEquipmentReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.QueryEquipmentReply}
 */
proto.Soit.System.QueryEquipmentReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protobuf_infrastructure_pb.PageResult;
      reader.readMessage(value,protobuf_infrastructure_pb.PageResult.deserializeBinaryFromReader);
      msg.setPageResult(value);
      break;
    case 2:
      var value = new proto.Soit.System.FindEquipmentReply;
      reader.readMessage(value,proto.Soit.System.FindEquipmentReply.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.QueryEquipmentReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.QueryEquipmentReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.QueryEquipmentReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.QueryEquipmentReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageResult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protobuf_infrastructure_pb.PageResult.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Soit.System.FindEquipmentReply.serializeBinaryToWriter
    );
  }
};


/**
 * optional PageResult page_result = 1;
 * @return {?proto.Soit.System.PageResult}
 */
proto.Soit.System.QueryEquipmentReply.prototype.getPageResult = function() {
  return /** @type{?proto.Soit.System.PageResult} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.PageResult, 1));
};


/**
 * @param {?proto.Soit.System.PageResult|undefined} value
 * @return {!proto.Soit.System.QueryEquipmentReply} returns this
*/
proto.Soit.System.QueryEquipmentReply.prototype.setPageResult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.System.QueryEquipmentReply} returns this
 */
proto.Soit.System.QueryEquipmentReply.prototype.clearPageResult = function() {
  return this.setPageResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.System.QueryEquipmentReply.prototype.hasPageResult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated FindEquipmentReply items = 2;
 * @return {!Array<!proto.Soit.System.FindEquipmentReply>}
 */
proto.Soit.System.QueryEquipmentReply.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.Soit.System.FindEquipmentReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Soit.System.FindEquipmentReply, 2));
};


/**
 * @param {!Array<!proto.Soit.System.FindEquipmentReply>} value
 * @return {!proto.Soit.System.QueryEquipmentReply} returns this
*/
proto.Soit.System.QueryEquipmentReply.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Soit.System.FindEquipmentReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.System.FindEquipmentReply}
 */
proto.Soit.System.QueryEquipmentReply.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Soit.System.FindEquipmentReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.System.QueryEquipmentReply} returns this
 */
proto.Soit.System.QueryEquipmentReply.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};


/**
 * @enum {number}
 */
proto.Soit.System.State = {
  NOTUSED: 0,
  USED: 1,
  ELIMINATE: 2
};

goog.object.extend(exports, proto.Soit.System);
