// source: protos/user.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var protobuf_infrastructure_pb = require('../protobuf/infrastructure_pb.js');
goog.object.extend(proto, protobuf_infrastructure_pb);
goog.exportSymbol('proto.Soit.System.CreateUserRequest', null, global);
goog.exportSymbol('proto.Soit.System.FindUserReply', null, global);
goog.exportSymbol('proto.Soit.System.QueryUserReply', null, global);
goog.exportSymbol('proto.Soit.System.QueryUserRequest', null, global);
goog.exportSymbol('proto.Soit.System.UpdateUserRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.CreateUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.System.CreateUserRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.System.CreateUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.CreateUserRequest.displayName = 'proto.Soit.System.CreateUserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.UpdateUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.System.UpdateUserRequest.repeatedFields_, null);
};
goog.inherits(proto.Soit.System.UpdateUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.UpdateUserRequest.displayName = 'proto.Soit.System.UpdateUserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.FindUserReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.System.FindUserReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.System.FindUserReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.FindUserReply.displayName = 'proto.Soit.System.FindUserReply';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.QueryUserRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Soit.System.QueryUserRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.QueryUserRequest.displayName = 'proto.Soit.System.QueryUserRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Soit.System.QueryUserReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Soit.System.QueryUserReply.repeatedFields_, null);
};
goog.inherits(proto.Soit.System.QueryUserReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Soit.System.QueryUserReply.displayName = 'proto.Soit.System.QueryUserReply';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.System.CreateUserRequest.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.CreateUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.CreateUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.CreateUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.CreateUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    entryDate: jspb.Message.getFieldWithDefault(msg, 2, 0),
    departureDate: jspb.Message.getFieldWithDefault(msg, 3, 0),
    mobile: jspb.Message.getFieldWithDefault(msg, 4, ""),
    idcard: jspb.Message.getFieldWithDefault(msg, 5, ""),
    job: jspb.Message.getFieldWithDefault(msg, 6, ""),
    computerIdsList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.CreateUserRequest}
 */
proto.Soit.System.CreateUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.CreateUserRequest;
  return proto.Soit.System.CreateUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.CreateUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.CreateUserRequest}
 */
proto.Soit.System.CreateUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEntryDate(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDepartureDate(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMobile(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdcard(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setJob(value);
      break;
    case 7:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addComputerIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.CreateUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.CreateUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.CreateUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.CreateUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEntryDate();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getDepartureDate();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getMobile();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getIdcard();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getJob();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getComputerIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      7,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.Soit.System.CreateUserRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int64 entry_date = 2;
 * @return {number}
 */
proto.Soit.System.CreateUserRequest.prototype.getEntryDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.setEntryDate = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 departure_date = 3;
 * @return {number}
 */
proto.Soit.System.CreateUserRequest.prototype.getDepartureDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.setDepartureDate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string mobile = 4;
 * @return {string}
 */
proto.Soit.System.CreateUserRequest.prototype.getMobile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.setMobile = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string idcard = 5;
 * @return {string}
 */
proto.Soit.System.CreateUserRequest.prototype.getIdcard = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.setIdcard = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string job = 6;
 * @return {string}
 */
proto.Soit.System.CreateUserRequest.prototype.getJob = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.setJob = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated int64 computer_ids = 7;
 * @return {!Array<number>}
 */
proto.Soit.System.CreateUserRequest.prototype.getComputerIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.setComputerIdsList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.addComputerIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.System.CreateUserRequest} returns this
 */
proto.Soit.System.CreateUserRequest.prototype.clearComputerIdsList = function() {
  return this.setComputerIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.System.UpdateUserRequest.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.UpdateUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.UpdateUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.UpdateUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.UpdateUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    entryDate: jspb.Message.getFieldWithDefault(msg, 3, 0),
    departureDate: jspb.Message.getFieldWithDefault(msg, 4, 0),
    mobile: jspb.Message.getFieldWithDefault(msg, 5, ""),
    idcard: jspb.Message.getFieldWithDefault(msg, 6, ""),
    job: jspb.Message.getFieldWithDefault(msg, 7, ""),
    computerIdsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.UpdateUserRequest}
 */
proto.Soit.System.UpdateUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.UpdateUserRequest;
  return proto.Soit.System.UpdateUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.UpdateUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.UpdateUserRequest}
 */
proto.Soit.System.UpdateUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEntryDate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDepartureDate(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMobile(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdcard(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setJob(value);
      break;
    case 8:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addComputerIds(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.UpdateUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.UpdateUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.UpdateUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.UpdateUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEntryDate();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getDepartureDate();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getMobile();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIdcard();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getJob();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getComputerIdsList();
  if (f.length > 0) {
    writer.writePackedInt64(
      8,
      f
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.System.UpdateUserRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Soit.System.UpdateUserRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 entry_date = 3;
 * @return {number}
 */
proto.Soit.System.UpdateUserRequest.prototype.getEntryDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.setEntryDate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 departure_date = 4;
 * @return {number}
 */
proto.Soit.System.UpdateUserRequest.prototype.getDepartureDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.setDepartureDate = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string mobile = 5;
 * @return {string}
 */
proto.Soit.System.UpdateUserRequest.prototype.getMobile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.setMobile = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string idcard = 6;
 * @return {string}
 */
proto.Soit.System.UpdateUserRequest.prototype.getIdcard = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.setIdcard = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string job = 7;
 * @return {string}
 */
proto.Soit.System.UpdateUserRequest.prototype.getJob = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.setJob = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated int64 computer_ids = 8;
 * @return {!Array<number>}
 */
proto.Soit.System.UpdateUserRequest.prototype.getComputerIdsList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.setComputerIdsList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.addComputerIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.System.UpdateUserRequest} returns this
 */
proto.Soit.System.UpdateUserRequest.prototype.clearComputerIdsList = function() {
  return this.setComputerIdsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.System.FindUserReply.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.FindUserReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.FindUserReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.FindUserReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.FindUserReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    entryDate: jspb.Message.getFieldWithDefault(msg, 3, 0),
    departureDate: jspb.Message.getFieldWithDefault(msg, 4, 0),
    mobile: jspb.Message.getFieldWithDefault(msg, 5, ""),
    idcard: jspb.Message.getFieldWithDefault(msg, 6, ""),
    job: jspb.Message.getFieldWithDefault(msg, 7, ""),
    computerIdsList: jspb.Message.toObjectList(msg.getComputerIdsList(),
    protobuf_infrastructure_pb.NamedIdentify.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.FindUserReply}
 */
proto.Soit.System.FindUserReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.FindUserReply;
  return proto.Soit.System.FindUserReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.FindUserReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.FindUserReply}
 */
proto.Soit.System.FindUserReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEntryDate(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDepartureDate(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMobile(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdcard(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setJob(value);
      break;
    case 8:
      var value = new protobuf_infrastructure_pb.NamedIdentify;
      reader.readMessage(value,protobuf_infrastructure_pb.NamedIdentify.deserializeBinaryFromReader);
      msg.addComputerIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.FindUserReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.FindUserReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.FindUserReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.FindUserReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEntryDate();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getDepartureDate();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getMobile();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getIdcard();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getJob();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getComputerIdsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      protobuf_infrastructure_pb.NamedIdentify.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 id = 1;
 * @return {number}
 */
proto.Soit.System.FindUserReply.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.FindUserReply} returns this
 */
proto.Soit.System.FindUserReply.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.Soit.System.FindUserReply.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindUserReply} returns this
 */
proto.Soit.System.FindUserReply.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 entry_date = 3;
 * @return {number}
 */
proto.Soit.System.FindUserReply.prototype.getEntryDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.FindUserReply} returns this
 */
proto.Soit.System.FindUserReply.prototype.setEntryDate = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 departure_date = 4;
 * @return {number}
 */
proto.Soit.System.FindUserReply.prototype.getDepartureDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Soit.System.FindUserReply} returns this
 */
proto.Soit.System.FindUserReply.prototype.setDepartureDate = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string mobile = 5;
 * @return {string}
 */
proto.Soit.System.FindUserReply.prototype.getMobile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindUserReply} returns this
 */
proto.Soit.System.FindUserReply.prototype.setMobile = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string idcard = 6;
 * @return {string}
 */
proto.Soit.System.FindUserReply.prototype.getIdcard = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindUserReply} returns this
 */
proto.Soit.System.FindUserReply.prototype.setIdcard = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string job = 7;
 * @return {string}
 */
proto.Soit.System.FindUserReply.prototype.getJob = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.FindUserReply} returns this
 */
proto.Soit.System.FindUserReply.prototype.setJob = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated NamedIdentify computer_ids = 8;
 * @return {!Array<!proto.Soit.System.NamedIdentify>}
 */
proto.Soit.System.FindUserReply.prototype.getComputerIdsList = function() {
  return /** @type{!Array<!proto.Soit.System.NamedIdentify>} */ (
    jspb.Message.getRepeatedWrapperField(this, protobuf_infrastructure_pb.NamedIdentify, 8));
};


/**
 * @param {!Array<!proto.Soit.System.NamedIdentify>} value
 * @return {!proto.Soit.System.FindUserReply} returns this
*/
proto.Soit.System.FindUserReply.prototype.setComputerIdsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.Soit.System.NamedIdentify=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.System.NamedIdentify}
 */
proto.Soit.System.FindUserReply.prototype.addComputerIds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.Soit.System.NamedIdentify, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.System.FindUserReply} returns this
 */
proto.Soit.System.FindUserReply.prototype.clearComputerIdsList = function() {
  return this.setComputerIdsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.QueryUserRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.QueryUserRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.QueryUserRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.QueryUserRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    contains: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orderRequest: (f = msg.getOrderRequest()) && protobuf_infrastructure_pb.OrderRequest.toObject(includeInstance, f),
    pageRequest: (f = msg.getPageRequest()) && protobuf_infrastructure_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.QueryUserRequest}
 */
proto.Soit.System.QueryUserRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.QueryUserRequest;
  return proto.Soit.System.QueryUserRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.QueryUserRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.QueryUserRequest}
 */
proto.Soit.System.QueryUserRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setContains(value);
      break;
    case 2:
      var value = new protobuf_infrastructure_pb.OrderRequest;
      reader.readMessage(value,protobuf_infrastructure_pb.OrderRequest.deserializeBinaryFromReader);
      msg.setOrderRequest(value);
      break;
    case 3:
      var value = new protobuf_infrastructure_pb.PageRequest;
      reader.readMessage(value,protobuf_infrastructure_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPageRequest(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.QueryUserRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.QueryUserRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.QueryUserRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.QueryUserRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContains();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOrderRequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      protobuf_infrastructure_pb.OrderRequest.serializeBinaryToWriter
    );
  }
  f = message.getPageRequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      protobuf_infrastructure_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string contains = 1;
 * @return {string}
 */
proto.Soit.System.QueryUserRequest.prototype.getContains = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Soit.System.QueryUserRequest} returns this
 */
proto.Soit.System.QueryUserRequest.prototype.setContains = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional OrderRequest order_request = 2;
 * @return {?proto.Soit.System.OrderRequest}
 */
proto.Soit.System.QueryUserRequest.prototype.getOrderRequest = function() {
  return /** @type{?proto.Soit.System.OrderRequest} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.OrderRequest, 2));
};


/**
 * @param {?proto.Soit.System.OrderRequest|undefined} value
 * @return {!proto.Soit.System.QueryUserRequest} returns this
*/
proto.Soit.System.QueryUserRequest.prototype.setOrderRequest = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.System.QueryUserRequest} returns this
 */
proto.Soit.System.QueryUserRequest.prototype.clearOrderRequest = function() {
  return this.setOrderRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.System.QueryUserRequest.prototype.hasOrderRequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional PageRequest page_request = 3;
 * @return {?proto.Soit.System.PageRequest}
 */
proto.Soit.System.QueryUserRequest.prototype.getPageRequest = function() {
  return /** @type{?proto.Soit.System.PageRequest} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.PageRequest, 3));
};


/**
 * @param {?proto.Soit.System.PageRequest|undefined} value
 * @return {!proto.Soit.System.QueryUserRequest} returns this
*/
proto.Soit.System.QueryUserRequest.prototype.setPageRequest = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.System.QueryUserRequest} returns this
 */
proto.Soit.System.QueryUserRequest.prototype.clearPageRequest = function() {
  return this.setPageRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.System.QueryUserRequest.prototype.hasPageRequest = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Soit.System.QueryUserReply.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Soit.System.QueryUserReply.prototype.toObject = function(opt_includeInstance) {
  return proto.Soit.System.QueryUserReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Soit.System.QueryUserReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.QueryUserReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    pageResult: (f = msg.getPageResult()) && protobuf_infrastructure_pb.PageResult.toObject(includeInstance, f),
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.Soit.System.FindUserReply.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Soit.System.QueryUserReply}
 */
proto.Soit.System.QueryUserReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Soit.System.QueryUserReply;
  return proto.Soit.System.QueryUserReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Soit.System.QueryUserReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Soit.System.QueryUserReply}
 */
proto.Soit.System.QueryUserReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new protobuf_infrastructure_pb.PageResult;
      reader.readMessage(value,protobuf_infrastructure_pb.PageResult.deserializeBinaryFromReader);
      msg.setPageResult(value);
      break;
    case 2:
      var value = new proto.Soit.System.FindUserReply;
      reader.readMessage(value,proto.Soit.System.FindUserReply.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Soit.System.QueryUserReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Soit.System.QueryUserReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Soit.System.QueryUserReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Soit.System.QueryUserReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPageResult();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      protobuf_infrastructure_pb.PageResult.serializeBinaryToWriter
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Soit.System.FindUserReply.serializeBinaryToWriter
    );
  }
};


/**
 * optional PageResult page_result = 1;
 * @return {?proto.Soit.System.PageResult}
 */
proto.Soit.System.QueryUserReply.prototype.getPageResult = function() {
  return /** @type{?proto.Soit.System.PageResult} */ (
    jspb.Message.getWrapperField(this, protobuf_infrastructure_pb.PageResult, 1));
};


/**
 * @param {?proto.Soit.System.PageResult|undefined} value
 * @return {!proto.Soit.System.QueryUserReply} returns this
*/
proto.Soit.System.QueryUserReply.prototype.setPageResult = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Soit.System.QueryUserReply} returns this
 */
proto.Soit.System.QueryUserReply.prototype.clearPageResult = function() {
  return this.setPageResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Soit.System.QueryUserReply.prototype.hasPageResult = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated FindUserReply items = 2;
 * @return {!Array<!proto.Soit.System.FindUserReply>}
 */
proto.Soit.System.QueryUserReply.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.Soit.System.FindUserReply>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Soit.System.FindUserReply, 2));
};


/**
 * @param {!Array<!proto.Soit.System.FindUserReply>} value
 * @return {!proto.Soit.System.QueryUserReply} returns this
*/
proto.Soit.System.QueryUserReply.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Soit.System.FindUserReply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Soit.System.FindUserReply}
 */
proto.Soit.System.QueryUserReply.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Soit.System.FindUserReply, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Soit.System.QueryUserReply} returns this
 */
proto.Soit.System.QueryUserReply.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};


goog.object.extend(exports, proto.Soit.System);
